### ISSUE TITLE
Index des participations + filtres (User)

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#14]
_En tant qu'utilisateur je peux voir toutes les participations publiées et les filtrer_

- [x] Afficher toutes les participations authorisées (statut : "authorized" ou "waiting for answer") MVP
- [x] Adapter la couleur du bouton "voir ..." en fonction du type de la participation
- [x] Retirer le filtre “Etat" et “Auteurs" => je crois qu'il peuvent simplement se désactiver en admin, à vérifier.
- [x] Rajouter un filtre par Type: Toutes/Réponse publiée/En attente de réponse
<img width="748" alt="screen shot 2018-01-17 at 07 43 44" src="https://user-images.githubusercontent.com/12518762/35029224-3996145a-fb5a-11e7-811e-9cfe1401c9ba.png">

Il faut probablement updater cette méthode (entre autres) : 
<img width="344" alt="screen shot 2018-01-15 at 14 00 29" src="https://user-images.githubusercontent.com/12518762/34943592-889ca604-f9fc-11e7-8664-9dd15d66f61f.png">
decidim-participations/app/controllers/decidim/participations/participations_controller.rb

**Comment by juliesimon** [comment]
Dans l'index des participations, sur les avis on devrait avoir un bouton "voir l'avis", et non "voir l'opinion" comme c'est le cas là 

![capture d ecran 2018-02-12 a 18 21 47](https://user-images.githubusercontent.com/29771726/36110096-c78f6cda-1021-11e8-8d07-38b10c9095d7.png)

**Comment by netbe** [comment]
@juliesimon y a une url où je peux voir le probleme? c'est quel projet / branche qui est deployée?

**Comment by juliesimon** [comment]
C'est bon pour cette issue, ça a été fixé par la PR All Fixes#65
