### ISSUE TITLE
Répondre à  une question (MOA ou CPDP)

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#17]
_En tant que MO/CPDP je veux pouvoir formuler des réponses aux questions_

Formulaire de rédaction de la réponse = Même vu pour MO et modérateur, mais avec des droits différents

Reprendre cette vue : https://demo.decidim.opensourcepolitics.eu/admin/participatory_processes/ConsultationNumerique/features/72/manage/proposals/109/proposal_answers/109/edit   => Attention les statuts présents sur cette vue sont ceux d'une proposition pas ceux de la réponse. Il faut donc les enlever.

Coté MO :
* Champ de saisi de la réponse
=> Envoi notif au modérateur
=> Changement de statut : "A valider"
  
<img width="509" alt="capture d ecran 2018-01-16 a 19 24 26" src="https://user-images.githubusercontent.com/11473995/35005228-0a7f001c-faf3-11e7-910c-4c31c61a83e3.png">

_En tant que modérateur je veux pouvoir accepter ou refuser des réponses_

Coté modérateur :
* body de la réponse
* Radio button  : "retenue" / "réponse incomplète"
* champ de justification si "demande de révision" cochée
=> Envoi mail au MO pour le prévenir que sa réponse a été acceptée OU pour demande de révision (+ justification dans le corps du mail)
=> Envoi mail à l'auteur de la question pour le prévenir qu'une réponse a été publiée

<img width="602" alt="capture d ecran 2018-01-16 a 19 26 03" src="https://user-images.githubusercontent.com/11473995/35005265-22ae7b68-faf3-11e7-98eb-213b301c5cd4.png">

/!\ La réponse ne doit être publiée que lorsque le statut est "accepted" (retenue)

-------------
Tips : la réponse est un attribut de l'objet participation  
```ruby
#<Decidim::Proposals::Proposal id: 30,... answered_at: "2018-01-05 12:46:01", answer: {"en"=>"Quia rem nemo quia repellendus deleniti vel deserunt quo similique unde.", "fr"=>"Dolores incidunt reiciendis tempore est quidem itaque et non provident."}>
```

**Comment by juliesimon** [comment]
@ludivinecp  j'avais commencé à splitter cette issue en plusieurs (une pour la réponse côté MOA, l'autre côté CPNP, l'autre pour la modération de la CPDP) => est ce que je continue ou comme c'est actuellement te convient plus ?
Et les écrans restent les mêmes, pas de changement

**Comment by ludivinecp** [comment]
On laisse comme ça car il s'agit de la même vue ;)
