### ISSUE TITLE
Gestions des droits

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#18]
_En tant qu'admin, je peux gérer les droits des utilisateurs (CPDP, modérateur, admin)

Checker que tous les droits d'accès soit respectés : 
<img width="598" alt="screen shot 2018-01-05 at 15 12 06" src="https://user-images.githubusercontent.com/12518762/34612602-d113e1e2-f22a-11e7-8c46-418b030a3e9d.png">

![Capture d’écran 2018-01-11 à 17.27.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4146fbe78a2cb4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163766e07e3e7c4e911c762e792a.png)
![Capture d’écran 2018-01-17 à 09.42.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132c410ea3febc41514140fee7882eb4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163765e7713f7c469318772e792a.png)
<img width="692" alt="capture d ecran 2018-02-13 a 14 08 54" src="https://user-images.githubusercontent.com/29771726/36151443-7eaee3b4-10c7-11e8-960b-a6db5d3b8f3a.png">

**Comment by juliesimon** [comment]
Les droits du modérateur sur SQR ne sont pas ok : dans les specs, le modérateur a les mêmes droits que CPDP, dont ceux de modération des propositions. Là (sur [osp-dcd-sqr-deploy.herokuapp.com](osp-dcd-sqr-deploy.herokuapp.com) le modérateur ne peut rien faire sur le module "participation" 
<img width="1041" alt="capture d ecran 2018-02-13 a 14 12 09" src="https://user-images.githubusercontent.com/29771726/36151563-fa8143c4-10c7-11e8-8f5b-7ed471ad67a6.png">

**Comment by juliesimon** [comment]
@ludivinecp de manière générale, on a des problèmes avec des actions admins qui restent accessibles après qu'elles aient été réalisée.
Par exemple ce problème qui vient de nous être remonté par la CPDP : 
La MOA répond à une question, elle est validée par la CPDP, la réponse est publiée.
La MOA peut ré-accéder à l'écran d'édition d'une réponse, à travers les notifications mail ou la petite 🔔 de la plateforme.
Elle arrive devant un champ où il y a déjà sa réponse. Elle la modifie.
La question avec la réponse éditée reste dans l'onglet "A traiter" (écran 1 - voir question n°15 en bas), par contre plus aucune réponse n'est affichée (écran 2).

<img width="685" alt="capture d ecran 2018-02-20 a 16 32 41" src="https://user-images.githubusercontent.com/29771726/36433384-a84a074a-165c-11e8-946e-13387178b57d.png">

<img width="670" alt="capture d ecran 2018-02-20 a 16 32 49" src="https://user-images.githubusercontent.com/29771726/36433418-bb899c94-165c-11e8-9cf0-2e17a71700fe.png">

**Comment by juliesimon** [comment]
@ludivinecp (je ne sais pas trop où mettre cette issue) : 
Ce problème vient de nous être remonté par la CPDP : 
La MOA répond à une question, elle est validée par la CPDP, la réponse est publiée.
La MOA peut ré-accéder à l'écran d'édition d'une réponse, à travers les notifications mail ou la petite 🔔 de la plateforme.
Elle arrive devant un champ où il y a déjà sa réponse. Elle la modifie.
La question avec la réponse éditée reste dans l'onglet "A traiter" (écran 1 - voir question n°15 en bas), par contre plus aucune réponse n'est affichée (écran 2).

<img width="685" alt="capture d ecran 2018-02-20 a 16 32 41" src="https://user-images.githubusercontent.com/29771726/36433384-a84a074a-165c-11e8-946e-13387178b57d.png">

<img width="670" alt="capture d ecran 2018-02-20 a 16 32 49" src="https://user-images.githubusercontent.com/29771726/36433418-bb899c94-165c-11e8-9cf0-2e17a71700fe.png">

Ce qu'il faudrait c'est que l'accès à l'edit d'une réponse (url de type: http://osp-dcd-sqr-deploy.herokuapp.com/admin/participatory_processes/pp1/features/16/manage/participations/34/participation_answers/34/edit) ne soit plus accessible une fois que la réponse a été publiée
