### ISSUE TITLE
Création des rôles

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#19]
Il faut créer de nouveaux rôles : MOA, CPDP...
Voir partie ACL du cahier des charges : https://docs.google.com/document/d/1zmCXUKcqTA0NVnVUIbjELv3qMK55Z3UmZfT_uzcLke4/edit

![Capture d’écran 2018-01-11 à 17.03.36.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144ffe78a2db4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e0445fa5163766e07e307a45931a742f792a.png)

**Comment by juliesimon** [comment]
J'ai transformé MO en MOA pour que ce soit plus clair qu'on parle bien de maîtrise d'ouvrage mais si jamais dans certaines issues il y a MO, lisez MOA

**Comment by netbe** [comment]
See https://github.com/OpenSourcePolitics/decidim-participations/tree/f-19-create-roles

To merge once the engine is renamed!
