### ISSUE TITLE
Répondre à une question (MOA)

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-participations#21]
En tant que MOA je peux répondre à une question et soumettre cette réponse à modération de la CPDP
<img width="509" alt="capture d ecran 2018-01-16 a 19 24 26" src="https://user-images.githubusercontent.com/11473995/35005193-ea247252-faf2-11e7-9836-fdc210edc8e1.png">

**Comment by ludivinecp** [comment]
duplicate #20
