### ISSUE TITLE
Vues des participations (User)

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-participations#23]
_En tant qu'utilisateur, je peux accéder à la vue de chaque participation_

=> Normalement tout sera ok, il faut simplement checker

![Capture d’écran 2018-01-11 à 17.00.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144fce78b2cb4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163766e07e3078419c1e752c792a.png)

![Capture d’écran 2018-01-11 à 17.00.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144fce78d22b4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e0445fa5163766e07e307840931c7524792a.png)

![Capture d’écran 2018-01-11 à 17.00.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144fce78c28b4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163766e07e30784f9417772a792a.png)

![Capture d’écran 2018-01-11 à 17.00.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144fce78a2fb4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e0455fa5163766e07e30784f901e762d792a.png)

![Capture d’écran 2018-01-11 à 17.00.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a532e69b133d50014ef1ee8/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b379f2132a410ea3febc405f4144fce78a23b4aa2e30c80351b882294d7ed43840a8ebd61ebf09e921d81cd1b3bc8a4fc9be3c2de1dd8a5d220c4749d7ab0268f9d31e8a4afc59e34f5fa5163766e07e30784f931f7425792a.png)

**Comment by hgueguen** [comment]
C'est ok pour l'utilisateur !
