### ISSUE TITLE
Dashboard (CPDP)

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#4]
_En tant que modérateur/CPDP, je peux voir la liste des participations reçues, dans mon dashboard._

Reprendre le dashboard de la modération à priori.

 3 onglets :

- [x] * **A traiter** (Toutes les participations non traitées)
   Actions :
   

- [x] Dupliquer ("l’intelligence" de ce bouton est gérée dans une autre issue)
   

- [x]  Editer ("l’intelligence" de ce bouton est gérée dans une autre issue)
    

- [x] Commencer une discussion avec l'auteur

![capture d ecran 2018-01-11 a 13 16 11](https://user-images.githubusercontent.com/29771726/34825211-d832fa70-f6d1-11e7-90bf-2739aa469eea.png)

- [x] * **Questions** (SOIT questions traitée mais en attente de réponse par CNDP/MOA, SOIT questions traitées et répondues par MOA mais en attente de validation par CNDP)
   Actions : 
 - [x]  * Répondre ("l’intelligence" de ce bouton est gérée dans une autre issue)
  If question en attente de réponse par modé/CNDP : 
 
  - [x]  * Voir la publication  ("l’intelligence" de ce bouton est gérée dans une autre issue)
   

- [x] *Commencer une discussion avec l'auteur ("l’intelligence" de ce bouton est gérée dans une autre issue)
![capture d ecran 2018-01-11 a 13 16 33](https://user-images.githubusercontent.com/29771726/34825169-a9e35fde-f6d1-11e7-8bbf-b5ef9ae6f3e3.png)

- [x] **Traités** (SOIT contenu publié ou refusé, SOIT questions publiées dont la réponse est publiée également)
   Actions : 
   

- [x] * Editer ("l’intelligence" de ce bouton est gérée dans une autre issue)
  

- [x] * Voir la publication  ("l’intelligence" de ce bouton est gérée dans une autre issue
![capture d ecran 2018-01-11 a 13 16 48](https://user-images.githubusercontent.com/29771726/34825184-b4c6b392-f6d1-11e7-8f93-c6ed604ef3a2.png)

**Comment by juliesimon** [comment]
@ludivinecp les specs et écrans sont à jour pour cette issue

**Comment by juliesimon** [comment]
Dans la colonne "destinataire" du tableau de bord onglet "Questions", "CPDP" et "MOA" doivent être en majuscule, comme des sigles. Actuellement ils sont en minuscule : 
<img width="1198" alt="capture d ecran 2018-02-14 a 10 48 49" src="https://user-images.githubusercontent.com/29771726/36197670-bb86097c-1174-11e8-972e-7a5fb9043dc2.png">

**Comment by juliesimon** [comment]
@ludivinecp
Dans l'onglet "Traitées", si la CPDP/admin modère une participation pour une seconde fois, elle prend le numéro de la dernière participation traitée. On se retrouve avec des participations qui ont le même numéro.
<img width="687" alt="capture d ecran 2018-02-20 a 17 13 50" src="https://user-images.githubusercontent.com/29771726/36435278-87ceb812-1661-11e8-9202-45f65943fd81.png">

Il faudrait qu'une fois qu'une participation a un numéro, il ne bouge plus !
