### ISSUE TITLE
All Fixes

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#42]
> @ludivinecp EDIT jeudi 25 janvier à 16:08 by @juliesimon

- [x]  Ré-harmoniser le JS => vue Edit (participation et réponse)
Les champs justification doivent avoir plus ou moins les mêmes comportements. Refacto le code JS  qui a été fait 

-----

- [x] Quand on est dans la page edit et que le type choisi est "question", si on coche "refusé", les radios buttons destinataire restent apparent

<img width="864" alt="screen shot 2018-01-24 at 19 21 52" src="https://user-images.githubusercontent.com/12518762/35349729-0b4b92fe-013c-11e8-99a1-a679080b7497.png">

-----

- [x] Certaines traductions sont mauvaises en Français : changer "opinion" par "avis"

-----

- [x] Depuis le dashboard "Traitées" lorsque je modifie une participation authorisée, sont statut passe à "refuser", même si je n'ai pas modifié le statut.

------

- [x] Vues des participations
Lorsque la réponse est encore en attente de validation, elle ne devrait pas s'afficher sur la vue de la question
<img width="826" alt="screen shot 2018-01-24 at 20 17 23" src="https://user-images.githubusercontent.com/12518762/35352447-3e7c255a-0144-11e8-8b8b-4274e0d7d991.png">

- [x] Dashboard, le filtre sur statut ne marche pas

------

- [x] quand je suis admin et que je clique sur "modifier" à côté d'une participation qui est dans "à traiter", la page d'édition (ou de modération, je ne sais pas comment l'appeler) de cette participation s'ouvre en target_blank => supprimer le target_blank

<img width="1440" alt="capture d ecran 2018-01-25 a 16 08 16" src="https://user-images.githubusercontent.com/29771726/35395201-f9d71bca-01e9-11e8-9634-2bee4f3a3364.png">

**Comment by ludivinecp** [comment]
@juliesimon 
Pour :
"quand je suis admin et que je clique sur "modifier" à côté d'une participation qui est dans "à traiter", la page d'édition (ou de modération, je ne sais pas comment l'appeler) de cette participation s'ouvre en target_blank => supprimer le target_blank"

J'ai repris le comportement présent sur tous les boutons déjà existant. Ce n'est pas qlq chose que j'ai changé.
Donc c'est plus cohérent de le garder non ?

**Comment by juliesimon** [comment]
Ok on laisse comme ça alors
