### ISSUE TITLE
Mailers

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#44]
specs : 
https://docs.google.com/document/d/1L1By0Lf1KQTPQH_pFkBJNC_4gAX-6FYJX0GaAjx6dbU/edit?ts=5a68b19e&pli=1#

**1/ Dépôt d’une participation**

- [x] En tant qu’utilisateur, je reçois un email m’informant que ma participation bien été soumise et est en attente de validation

Bonjour [nom-de-l'auteur-de-la-participation],
Votre participation a bien été soumise et est en attente de modération.

- [x] En tant que modérateur/CNDP, je reçois un email m’informant qu’une proposition a été faite 

Bonjour,
[nom-de-l'auteur-de-la-participation] a publié une nouvelle question dans [Titre processus participatif].
Traiter la participation

**2/ Publication d’une participation**

- [x] En tant qu’utilisateur, je reçois un email m’informant que ma proposition a été publiée/éditée/refusée + justification

Bonjour [nom-de-l'auteur-de-la-participation],
[Si participation publiée] Votre participation dans [Titre processus participatif] a été publiée.
Cliquez ici pour la consulter

- [x] [Si participation modérée] Votre participation dans [Titre processus participatif] a été publiée après modération de la CPDP, pour le(s) motif(s) suivant(s) :
ex: “La question originale a été divisée en deux questions distinctes pour plus de compréhension”
Cliquez ici pour la consulter

- [x] [Si participation refusée] Votre participation dans [Titre processus participatif] a été refusée après modération de la CPDP,  pour le motif suivant : 
“ La proposition de l’auteur reprenait une proposition déjà existante, visible au lien suivant : http://www….”

**3/ Publication d’une question**

- [x] En tant que MOA/CPDP, je reçois un email m’informant que je dois répondre à une question

	Bonjour,
La question n°# publiée dans [Titre processus participatif] attend une réponse de votre part.
Vous pouvez y répondre en suivant ce lien
--
Cliquez ici pour la consulter

**4/ Proposition de réponse par le MOA**

- [x] En tant que modérateur/CNDP, je reçois un email m’informant que je dois modérer une réponse de la MOA

	Bonjour,
La maîtrise d’ouvrage a soumis une réponse à la question n°# publiée dans [Titre processus participatif]
Vous pouvez la modérer en suivant ce lien
--
Cliquez ici pour la consulter

**5/ Traitement de la réponse du MOA par CPDP ou modérateur**

- [x] En tant que MOA, je reçois un email m’informant que ma réponse est publiée/qu’elle doit être complétée
Bonjour,
Votre réponse à la question n°# dans [Titre processus participatif] a été jugée insuffisante par la CPDP pour le motif suivant : 
“La date de lancement du chantier de la phase 2, demandée par l’auteur de la question, n’est pas renseignée dans votre réponse”
Vous pouvez éditer votre réponse en suivant ce lien
--
Cliquez ici pour consulter la question
Votre réponse à la question n°# dans [Titre processus participatif] a été validée par la CPDP
Cliquez ici pour la consulter

- [x] En tant qu’utilisateur, je reçois un email m’informant que ma question a reçu une réponse
Bonjour [nom-de-l'auteur-de-la-participation],
	Vous avez reçu une réponse pour votre question publiée dans [Titre processus participatif] :
Cliquez ici pour la consulter

- [ ]  Traduire le ficher de trad anglais

**Comment by netbe** [comment]
To create a mailer:

1) create an event class containing the content of the mail (translations)
2) send an email via the ` Decidim::EventsManager` with `extra` hash attribute `template`. This defines the email view (template) your going to use.


```
 Decidim::EventsManager.publish(
            event: "decidim.events.participations.participation_created",		  
            event_class: Decidim::Participations::ParticipationCreatedEvent,
            resource: @participation,		            resource: @participation,
            recipient_ids: (@participation.users_to_notify_on_participation_created - [@participation.author]).pluck(:id),
            extra: {
              template: "participation_created_event_moderator",            
              participatory_process_title: participatory_space_title,
              process_slug: @participation.feature.participatory_space.slug
            }		 
)
```

3) create a template under `app/views/decidim/notification_mailer`

Note: you cannot render links inside the translation, you need to use `link_to` helper in view
Note 2: for url, use the EngineRouter to generate the right url.
