### ISSUE TITLE
Réajustement UX peut être non urgent

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-participations#57]
J'ai fait les tests, tout marche au top (sauf les commentaires) !

J'ai remarqués deux-trois choses qui pourraient êtres améliorées mais pas urgentes

- En tant que CPDP je ne peux pas répondre pour MOA
Alors que pour l'instant, c'est possible
<img width="1046" alt="capture d ecran 2018-01-31 a 11 16 02" src="https://user-images.githubusercontent.com/29771726/35619939-d13c56ea-067f-11e8-8b6e-d8254e98ffad.png">

- EN tant que CPDP, pas besoin de marquer ma réponse comme incomplète
Pour l'instant, c'est possible

- Bouton : EN tant que CNDP, publier au lieu de soumettre lors de la non-validation réponse MOA
<img width="1046" alt="capture d ecran 2018-01-31 a 11 28 58" src="https://user-images.githubusercontent.com/29771726/35619988-f8d73e0e-067f-11e8-9b48-0f5ace9f9430.png">

- Question de la MOA en attente de validation dans Questions et non "a traiter"
<img width="1046" alt="capture d ecran 2018-01-31 a 11 32 59" src="https://user-images.githubusercontent.com/29771726/35620004-03fdf08e-0680-11e8-9c7e-84bae37cd1a3.png">

**Comment by ludivinecp** [comment]
@juliesimon Le CPDP a les mêmes droits que le modérateur sur les participations => https://github.com/OpenSourcePolitics/decidim-participations/issues/18
Ces comportements sont donc normaux.

En revanche je ne comprends pas le dernier point  : "Question de la MOA en attente de validation dans Questions et non "a traiter" "
Les questions en attente de validation sont bien affichées dans "Questions", ta photo le montre également. Sachant qu'en tant que MOA tu n'as pas l'onglet à traité. N'hésite pas à préciser ce point stp

**Comment by juliesimon** [comment]
Pardon, je faisais autre chose en même temps, je me suis trompée : pour moi les questions en attente de validation sont dans à "traiter", pas dans "questions". Sauf que si MOA n'a pas "à traiter", c'est surement mieux que les questions aient le même comportement chez MOA et CPDP.
Donc on laisse comme ça

**Comment by ludivinecp** [comment]
@juliesimon ok je close alors
