### ISSUE TITLE
Duplication des participations (CPDP)

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#6]
_En tant que modérateur je peux dupliquer une participation_

- [x] Le modérateur devra pouvoir dupliquer une participation et  modifier les objets dupliqués de manière indépendante. L’original devra être conservé.
Exemple : Si un utilisateur envoie une question et un avis dans un même formulaire, le modérateur peut les séparer en 2 participations distinctes et les recatégoriser si besoin.
- [x]  Dashboard :  Bouton de duplication  <img width="33" alt="screen shot 2018-01-05 at 08 25 53" src="https://user-images.githubusercontent.com/12518762/34600582-9c022946-f1f8-11e7-8749-f0691907c030.png">

- [ ]  Mailer à l’auteur seulement si la participation a été modifiée / dupliquée (“Votre participation a été modifié car…”)
Si la participation a été découpée en 5,  le participant reçoit 5 mails de modification afin d'avoir le lien de chaque participation correspondant à sa participation originale. 

Droit = modérateur

**Comment by juliesimon** [comment]
@ludivine : oui si la participation a été découpée en 5, le participant reçoit quand même 5 mails de modification afin d'avoir le lien de chaque participation correspondant à sa participation originale. Pas de désactivation du champ "justification" donc

**Comment by ludivinecp** [comment]
j'ai updaté l'issue en fonction
