### ISSUE TITLE
Mauvaise redirection

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#60]
En tant que MOA et CPDP, lorsque je me connecte à l'admin, je clique sur l'onglet "processus participatif" => titre du processus. Et au lieu d'arriver sur le dashboard des participations, j'arrive sur le tableau de modération à postériori (ce qui n'a rien à voir).

<img width="1272" alt="screen shot 2018-02-02 at 11 25 00" src="https://user-images.githubusercontent.com/12518762/35728504-1005727a-080c-11e8-949e-e603a18dbc48.png">

L'utilisateur devrait donc arriver directement ici : 
<img width="1280" alt="screen shot 2018-02-02 at 11 28 53" src="https://user-images.githubusercontent.com/12518762/35728564-447d9ab4-080c-11e8-89b3-1cb4dff86aa3.png">

**Comment by hgueguen** [comment]
Resolved in : https://github.com/OpenSourcePolitics/decidim-participations/pull/61

**Comment by ludivinecp** [comment]
@hgueguen  J'ai réouverte cette issue car il y a un petit bug : https://github.com/OpenSourcePolitics/decidim-participations/pull/61#pullrequestreview-97511287
