### ISSUE TITLE
Bugs mails SQR

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim-participations#63]
- [x] Certains mails de notification SQR ne sont pas envoyés
Il manque les mails suivants https://docs.google.com/spreadsheets/d/1oiZOsxwkBeVSH1B3Lzu2mo6wl4ZAoqQT0fMPzmz3GoM/edit#gid=1097769486 --> Apparemment c'est  ArgumentError (SMTP From address may not be blank: nil):
![logs heroku erreur mails non envoyes](https://user-images.githubusercontent.com/29771726/36108211-8fe6ce9a-101c-11e8-8742-604040ed9cc7.png)

**Comment by juliesimon** [comment]
- [ ] Le lien dans les mails de notification de publication d'une participation redirige vers l'index des participation et non vers la show de la participation en elle même comme la logique le voudrait. 
_(Non urgent, si c'est simple à changer on appliquera la modification)_

![capture d ecran 2018-02-12 a 17 54 55](https://user-images.githubusercontent.com/29771726/36108752-dc26348e-101d-11e8-90c4-4470abb40f07.png)

**Comment by juliesimon** [comment]
[] - En tant que MOA je ne devrais pas recevoir de mail m'indiquant un nouveau contenu.
Là c'est le cas, et quand je clique sur le lien, j'arrive bien à la page de modération d'un nouveau contenu (alors que je n'en ai normalement pas les droits)

<img width="1022" alt="capture d ecran 2018-02-14 a 17 34 27" src="https://user-images.githubusercontent.com/29771726/36215884-9e8dcd8a-11ad-11e8-8364-03abda7bdfd1.png">

**Comment by virgile-dev** [comment]
- [ ] quand une nouvelle participation est publiée par un utilisateur un email est envoyé aux utilisateurs CPDP, modérateurs et administrateurs pour qu'ils la traitent. Le truc c'est qu'avec la nouvelle version de Decidim un utilisateur peut modifier sa proposition pendant x minute (paramètre fixé en admin). Un problème se pose si la participation est traitée pendant le délai de modification et que l'utilisateur réalise une modification. Il faudrait donc que l'email soit envoyé une fois que la période de modification est expirée (sachant que l'utilisateur peut cliquer plusieurs fois sur le bouton modifier et que je ne sais pas si le compteur repart à 0 à chaque fois).

**Comment by juliesimon** [comment]
Pour le POINT 4 (delay dans les mails), ça ne marche pas, je reçois le mail de notification immédiatement après que l'utilisateur est posté sa participation, alors qu'elle est encore modifiable

**Comment by juliesimon** [comment]
@ludivinecp la question du delay du mail ne résous pas tout puisque finalement, parce que même si l'email est reçu à la fin de la période de modification, la participation s'affiche immédiatement, non ?

**Comment by ludivinecp** [comment]
@hgueguen  Juste pour info t'en ai ou sur le point 2 ?
