### ISSUE TITLE
Bug notif en tant que modérateur et admin

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#77]
Quand on clique sur la cloche pour accéder aux notifs : 
<img width="1128" alt="screen shot 2018-02-23 at 12 48 31" src="https://user-images.githubusercontent.com/12518762/36594894-eea8e476-1897-11e8-8a3a-085f47a1028c.png">

**Comment by juliesimon** [comment]
@ludivinecp en prod, tant qu'utilisateur, on ne voit aucune notification non plus
