### ISSUE TITLE
Attribution des questions (CPDP)

### ISSUE THREAD

**Issue by ludivinecp** [OpenSourcePolitics/decidim-participations#9]
_En tant que modérateur/CPDP, je peux attribuer une question à un MOA ou CPDP_

- [x]   Formulaire d’édition : si le type sélectionné == “Question” afficher ou non le Champ d’attribution
            (Il faut également attribuer la question à une personne en particulier / Spec visuel à revoir)
<img width="508" alt="screen shot 2018-01-05 at 09 35 41" src="https://user-images.githubusercontent.com/12518762/34601360-e03abf62-f1fb-11e7-8b47-154da2502501.png">

- [ ] Chaque question doit être attribué à une personne afin de pouvoir passer au statut "waiting for moderation"

- [ ] Mailer d’attribution à destination du MOA (Spec mailer à venir)

- [ ] Les questions doivent s'afficher dans le dashboard du MOA correspondant

**Comment by netbe** [comment]
> (Il faut également attribuer la question à une personne en particulier / Spec visuel à revoir)
On ne fera pas ca finalement

**Comment by netbe** [comment]
Related to #5 
@ludivinecp let me know when/which branch I can use to do that

**Comment by netbe** [comment]
>  Chaque question doit être attribué à une personne afin de pouvoir passer au statut "waiting for moderation"

Discussed with @virgile-dev, we dont do it

**Comment by ludivinecp** [comment]
@netbe What is the new spec ? We just attribute the question to a user role ? Not a specific person ?
You can use `develop` branch

**Comment by netbe** [comment]
@ludivinecp Yes, @virgile-dev said that moderator will have a mailing list in their mail.

But now I see what you mean.

We could either as you said:

1. set to a role, and then when we send the mail we send it to all users with that role
2. or present a list of user with Maitre d'ouvrage or CPDP?

@virgile-dev what do you think?

**Comment by virgile-dev** [comment]
@ludivinecp @netbe definitly the first option. You click on the role and the email is sent to all users that have that role in the participatory process.
